### ISSUE TITLE
CSR1000v default SSH redirect to router console or other workaround

### ISSUE THREAD

**Issue by mpenning-at-c1** [hellt/vrnetlab#182]
I may be missing something very obvious, but I've been trying to find a way to SSH directly to a Cisco CSR 1000V that I have running in containerlab.

ASCII art...

```none
+---------------------------+  eth2
|   csr01                   |------------------{ insert-more-topology-here }
|  mgmt-ipv4: 192.0.2.2/24  |
+---------------------------+
          | eth1
          |
```

The image is:
- CSR 1000v image -> `csr1000v-universalk9.17.03.08a-serial.qcow2`
- containerlab version: `0.53.0`
- Host OS: `Ubuntu 22.04.04 LTS` under Windows 11 WSL

I can `telnet 192.0.2.2 5000` and get to the console on the router after it boots; however, I can't figure out how I can directly ssh to the router with a blank router configuration.  Direct SSH is needed to get ansible working right because `ansible.netcommon.telnet` can't make things work on port 5000 for some reason.

Part of my problem is that this CSR 1000v image ignores practically all interface configuration in `startup-config`.  As such, I want to use ansible to configure the interfaces after the CSR 1000v boots, then I will have a routed topology that I can set a host route for in Ubuntu and ssh directly through the containerlab topology.

Is there a way to SSH to 192.0.2.2 port 22 and then run a bash command to get to the console of the CSR 1000v?  Any kind of SSH hack might be a workaround for status quo...

Snip from my topology yml file...

```yaml
name: rr

mgmt:
  network: statics
  ipv4-subnet: 192.0.2.0/24

topology:
  nodes:
    csr01:
      kind: vr-csr
      image: vrnetlab/vr-csr:17.03.08
      startup-config: config/csr01/config.txt
      mgmt-ipv4: 192.0.2.2
    csr02:
      kind: vr-csr
      image: vrnetlab/vr-csr:17.03.08
      startup-config: config/csr02/config.txt
      mgmt-ipv4: 192.0.2.3
    br-clab:
      kind: bridge

  links:
    - endpoints: ["csr01:eth2", "csr02:eth2"]
    - endpoints: ["br-clab:eth1", "csr01:eth1"]
    - endpoints: ["br-clab:eth2", "csr02:eth1"]
```

My contents of `config/csr01/config.txt`...

```none
hostname csr01
!
username cisco passsword cisco123
!
enable password cisco123
!
cdp run
!
aaa new-model
aaa authentication login default local enable
aaa authentication exec default local enable
aaa authorization console
!
line con 0
 transport input telnet
 password cisco123
 login
!
line vty 0 4
 transport input telnet
 password cisco123
 login
!
end
```
